export const ADMIN_USER_LOGIN_REQUEST = "ADMIN_USER_LOGIN_REQUEST";
export const ADMIN_USER_LOGIN_SUCCESS = "ADMIN_USER_LOGIN_SUCCESS";
export const ADMIN_USER_LOGIN_FAIL = "ADMIN_USER_LOGIN_FAIL";

export const ADMIN_USER_LOGOUT = "ADMIN_USER_LOGOUT";

export const ADMIN_USER_REGISTER_REQUEST = "ADMIN_USER_REGISTER_REQUEST";
export const ADMIN_USER_REGISTER_SUCCESS = "ADMIN_USER_REGISTER_SUCCESS";
export const ADMIN_USER_REGISTER_FAIL = "ADMIN_USER_REGISTER_FAIL";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";
