export const FEEDBACK_CREATE_REQUEST = "FEEDBACK_CREATE_REQUEST";
export const FEEDBACK_CREATE_SUCCESS = "FEEDBACK_CREATE_SUCCESS";
export const FEEDBACK_CREATE_FAIL = "FEEDBACK_CREATE_FAIL";
export const FEEDBACK_CREATE_RESET = "FEEDBACK_CREATE_RESET";

export const FEEDBACK_DETAILS_REQUEST = "FEEDBACK_DETAILS_REQUEST";
export const FEEDBACK_DETAILS_SUCCESS = "FEEDBACK_DETAILS_SUCCESS";
export const FEEDBACK_DETAILS_FAIL = "FEEDBACK_DETAILS_FAIL";

export const FEEDBACK_LIST_USER_REQUEST = "FEEDBACK_LIST_USER_REQUEST";
export const FEEDBACK_LIST_USER_SUCCESS = "FEEDBACK_LIST_USER_SUCCESS";
export const FEEDBACK_LIST_USER_FAIL = "FEEDBACK_LIST_USER_FAIL";
export const FEEDBACK_LIST_USER_RESET = "FEEDBACK_LIST_USER_RESET";

export const FEEDBACK_LIST_TECHNICIAN_REQUEST =
  "FEEDBACK_LIST_TECHNICIAN_REQUEST";
export const FEEDBACK_LIST_TECHNICIAN_SUCCESS =
  "FEEDBACK_LIST_TECHNICIAN_SUCCESS";
export const FEEDBACK_LIST_TECHNICIAN_FAIL = "FEEDBACK_LIST_TECHNICIAN_FAIL";
export const FEEDBACK_LIST_TECHNICIAN_RESET = "FEEDBACK_LIST_TECHNICIAN_RESET";

export const FEEDBACK_LIST_REQUEST = "FEEDBACK_LIST_REQUEST";
export const FEEDBACK_LIST_SUCCESS = "FEEDBACK_LIST_SUCCESS";
export const FEEDBACK_LIST_FAIL = "FEEDBACK_LIST_FAIL";
export const FEEDBACK_LIST_RESET = "FEEDBACK_LIST_RESET";

export const FEEDBACK_STATUS_UPDATE_REQUEST = "FEEDBACK_STATUS_UPDATE_REQUEST";
export const FEEDBACK_STATUS_UPDATE_SUCCESS = "FEEDBACK_STATUS_UPDATE_SUCCESS";
export const FEEDBACK_STATUS_UPDATE_FAIL = "FEEDBACK_STATUS_UPDATE_FAIL";
export const FEEDBACK_STATUS_UPDATE_RESET = "FEEDBACK_STATUS_UPDATE_RESET";

export const FEEDBACK_DELETE_REQUEST = "FEEDBACK_DELETE_REQUEST";
export const FEEDBACK_DELETE_SUCCESS = "FEEDBACK_DELETE_SUCCESS";
export const FEEDBACK_DELETE_FAIL = "FEEDBACK_DELETE_FAIL";
