export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_LIST_USER_REQUEST = "ORDER_LIST_USER_REQUEST";
export const ORDER_LIST_USER_SUCCESS = "ORDER_LIST_USER_SUCCESS";
export const ORDER_LIST_USER_FAIL = "ORDER_LIST_USER_FAIL";
export const ORDER_LIST_USER_RESET = "ORDER_LIST_USER_RESET";

export const ORDER_LIST_TECHNICIAN_REQUEST = "ORDER_LIST_TECHNICIAN_REQUEST";
export const ORDER_LIST_TECHNICIAN_SUCCESS = "ORDER_LIST_TECHNICIAN_SUCCESS";
export const ORDER_LIST_TECHNICIAN_FAIL = "ORDER_LIST_TECHNICIAN_FAIL";
export const ORDER_LIST_TECHNICIAN_RESET = "ORDER_LIST_TECHNICIAN_RESET";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";
export const ORDER_LIST_RESET = "ORDER_LIST_RESET";

export const ORDER_DONE_REQUEST = "ORDER_DONE_REQUEST";
export const ORDER_DONE_SUCCESS = "ORDER_DONE_SUCCESS";
export const ORDER_DONE_FAIL = "ORDER_DONE_FAIL";
export const ORDER_DONE_RESET = "ORDER_DONE_RESET";

export const ORDER_DELETE_REQUEST = "ORDER_DELETE_REQUEST";
export const ORDER_DELETE_SUCCESS = "ORDER_DELETE_SUCCESS";
export const ORDER_DELETE_FAIL = "ORDER_DELETE_FAIL";
