export const TECHNICIAN_LOGIN_REQUEST = "TECHNICIAN_LOGIN_REQUEST";
export const TECHNICIAN_LOGIN_SUCCESS = "TECHNICIAN_LOGIN_SUCCESS";
export const TECHNICIAN_LOGIN_FAIL = "TECHNICIAN_LOGIN_FAIL";

export const TECHNICIAN_LOGOUT = "TECHNICIAN_LOGOUT";

export const TECHNICIAN_REGISTER_REQUEST = "TECHNICIAN_REGISTER_REQUEST";
export const TECHNICIAN_REGISTER_SUCCESS = "TECHNICIAN_REGISTER_SUCCESS";
export const TECHNICIAN_REGISTER_FAIL = "TECHNICIAN_REGISTER_FAIL";

export const TECHNICIAN_UPDATE_PROFILE_REQUEST =
  "TECHNICIAN_UPDATE_PROFILE_REQUEST";
export const TECHNICIAN_UPDATE_PROFILE_SUCCESS =
  "TECHNICIAN_UPDATE_PROFILE_SUCCESS";
export const TECHNICIAN_UPDATE_PROFILE_FAIL = "TECHNICIAN_UPDATE_PROFILE_FAIL";
export const TECHNICIAN_UPDATE_PROFILE_RESET =
  "TECHNICIAN_UPDATE_PROFILE_RESET";

export const TECHNICIAN_LIST_REQUEST = "TECHNICIAN_LIST_REQUEST";
export const TECHNICIAN_LIST_SUCCESS = "TECHNICIAN_LIST_SUCCESS";
export const TECHNICIAN_LIST_FAIL = "TECHNICIAN_LIST_FAIL";

export const TECHNICIAN_SUPSCRIPTION_REQUEST =
  "TECHNICIAN_SUPSCRIPTION_REQUEST";
export const TECHNICIAN_SUPSCRIPTION_SUCCESS =
  "TECHNICIAN_SUPSCRIPTION_SUCCESS";
export const TECHNICIAN_SUPSCRIPTION_FAIL = "TECHNICIAN_SUPSCRIPTION_FAIL";

export const TECHNICIAN_DETAILS_REQUEST = "TECHNICIAN_DETAILS_REQUEST";
export const TECHNICIAN_DETAILS_SUCCESS = "TECHNICIAN_DETAILS_SUCCESS";
export const TECHNICIAN_DETAILS_FAIL = "TECHNICIAN_DETAILS_FAIL";
export const TECHNICIAN_DETAILS_RESET = "TECHNICIAN_DETAILS_RESET";

export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";
