export const TECHNICIAN_LOGIN_REQUEST = "TECHNICIAN_LOGIN_REQUEST";
export const TECHNICIAN_LOGIN_SUCCESS = "TECHNICIAN_LOGIN_SUCCESS";
export const TECHNICIAN_LOGIN_FAIL = "TECHNICIAN_LOGIN_FAIL";

export const TECHNICIAN_LOGOUT = "TECHNICIAN_LOGOUT";

export const TECHNICIAN_REGISTER_REQUEST = "TECHNICIAN_REGISTER_REQUEST";
export const TECHNICIAN_REGISTER_SUCCESS = "TECHNICIAN_REGISTER_SUCCESS";
export const TECHNICIAN_REGISTER_FAIL = "TECHNICIAN_REGISTER_FAIL";

export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";
